//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsExtractorDIrect
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsideData
    {
        public int ID { get; set; }
        public string Webside__Web_side__website___ { get; set; }
        public string Document_Node { get; set; }
        public string companyWebSite { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
